version: '3.8'

services:
  # Основное приложение
  ozmakon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozmakon
    restart: unless-stopped
    ports:
      - '80'  # Expose port 80 internally for nginx proxy
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - service_network
      - public_network

networks:
  service_network:
    external: true
    name: service_network
  public_network:
    external: true
    name: public_network
