version: '3.8'

services:
  ozmakon:
    build:
      context: .
      dockerfile: Dockerfile.777
    container_name: ozmakon-777
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
